-- bookmarks_schema.sql

-- Drop the table if it exists to start fresh
DROP TABLE IF EXISTS bookmarks;

-- Create the bookmarks table
CREATE TABLE bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    service_id TEXT NOT NULL,
    service_name TEXT,
    category TEXT,
    provider TEXT,
    city TEXT,
    price FLOAT,
    rating FLOAT,
    metadata JSONB, -- For any other service-specific details
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create an index on user_id for faster lookups
CREATE INDEX idx_bookmarks_user_id ON bookmarks(user_id);

-- Enable Row-Level Security (RLS)
ALTER TABLE bookmarks ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- Policy: Users can see their own bookmarks
CREATE POLICY "Users can view their own bookmarks"
ON bookmarks FOR SELECT
USING (auth.uid() = user_id);

-- Policy: Users can insert their own bookmarks
CREATE POLICY "Users can insert their own bookmarks"
ON bookmarks FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own bookmarks
CREATE POLICY "Users can delete their own bookmarks"
ON bookmarks FOR DELETE
USING (auth.uid() = user_id);

-- Grant access to the 'authenticated' role
GRANT SELECT, INSERT, UPDATE, DELETE ON bookmarks TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE bookmarks_id_seq TO authenticated;
